"""Typer CLI: the primary contract for the M1 milestone."""

from __future__ import annotations

import sys

import typer
from typer.core import TyperGroup

from novel_editorial import __version__
from novel_editorial.core.chat import (
    AUTHOR_ACTOR,
    PROACTIVE_PAYLOAD,
    PROACTIVE_QUESTION,
    build_agent_prompt,
    get_agent,
    get_workspace_or_raise,
    has_proactive_message,
    list_messages,
    record_message,
    resolve_target_role,
)
from novel_editorial.core.config import load_settings
from novel_editorial.core.errors import ErrorCode, NovelError
from novel_editorial.core.logging_setup import configure_logging
from novel_editorial.llm.client import LLMMessage, build_client
from novel_editorial.store.db import DB, seed_default_band
from novel_editorial.store.models import Agent, AgentRole, Workspace

reconfigure = getattr(sys.stdout, "reconfigure", None)
if callable(reconfigure):
    reconfigure(encoding="utf-8", errors="replace")


class NovelGroup(TyperGroup):
    """Translate NovelError to exit code 1 and unexpected errors to exit code 3."""

    def invoke(self, ctx) -> None:
        try:
            super().invoke(ctx)
        except (typer.Exit, typer.Abort):
            raise
        except NovelError as exc:
            typer.echo(f"Error: {exc.message}", err=True)
            exit_code = 2 if exc.code is ErrorCode.USAGE_ERROR else 1
            raise typer.Exit(exit_code) from exc
        except Exception as exc:
            typer.echo(f"Unexpected error: {exc}", err=True)
            raise typer.Exit(3) from exc


app = typer.Typer(cls=NovelGroup, help="Novel Editorial: a layered AI literary editorial office")
works_app = typer.Typer(help="Manage workspaces")
agents_app = typer.Typer(help="Manage editorial partners")
talk_app = typer.Typer(help="Talk with the editorial band")
app.add_typer(works_app, name="works")
app.add_typer(agents_app, name="agents")
app.add_typer(talk_app, name="talk")


@app.callback(invoke_without_command=True)
def main(
    verbose: bool = typer.Option(False, "--verbose", help="Enable debug logging"),
    show_version: bool = typer.Option(False, "--version", help="Show version and exit"),
) -> None:
    if show_version:
        typer.echo(__version__)
        raise typer.Exit()
    settings = load_settings()
    configure_logging("DEBUG" if verbose else settings.log_level)


@app.command("init")
def init() -> None:
    """Initialize data directory and configuration."""
    settings = load_settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    DB(settings).init_schema()
    if settings.config_path.exists():
        typer.echo(f"config exists: {settings.config_path} (kept)")
    else:
        settings.config_path.write_text(
            "# Generated by `novel-editorial init`. Copy config.example.toml for defaults.\n"
            "[defaults]\n",
            encoding="utf-8",
        )
    typer.echo(f"initialized: {settings.data_dir}")


@app.command()
def health() -> None:
    """Check configuration and database connectivity."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    db.ping()
    typer.echo("ok")


@app.command("version")
def version() -> None:
    """Print the current version."""
    typer.echo(__version__)


@works_app.command("create")
def works_create(
    title: str = typer.Argument(..., help="Work title"),
    genre: str = typer.Option("", "--genre", help="Genre"),
    description: str = typer.Option("", "--description", help="Short description"),
) -> None:
    """Create a workspace with a default editorial band."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspace = Workspace(title=title, genre=genre, description=description)
        session.add(workspace)
        session.commit()
        workspace_id = workspace.id
    db.create_workspace_db(workspace_id)
    seed_default_band(db, workspace_id)
    typer.echo(f"created workspace {workspace_id}: {title}")


@works_app.command("list")
def works_list() -> None:
    """List all workspaces."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspaces = session.query(Workspace).order_by(Workspace.created_at).all()
    for workspace in workspaces:
        typer.echo(f"{workspace.id}  {workspace.title}  {workspace.genre}")
    if not workspaces:
        typer.echo("no workspaces yet")


@works_app.command("show")
def works_show(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show a workspace and its editorial band."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspace = session.get(Workspace, workspace_id)
        if workspace is None:
            raise NovelError(ErrorCode.NOT_FOUND, f"workspace not found: {workspace_id}")
        title = workspace.title
        genre = workspace.genre
        description = workspace.description
    typer.echo(f"id: {workspace_id}")
    typer.echo(f"title: {title}")
    typer.echo(f"genre: {genre}")
    if description:
        typer.echo(f"description: {description}")
    with db.workspace_session(workspace_id) as session:
        agents = session.query(Agent).order_by(Agent.created_at).all()
    typer.echo("band:")
    for agent in agents:
        typer.echo(f"  {agent.role}: {agent.name}")


@agents_app.command("show")
def agents_show(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show the workspace's editorial band with full profiles."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        if session.get(Workspace, workspace_id) is None:
            raise NovelError(ErrorCode.NOT_FOUND, f"workspace not found: {workspace_id}")
    with db.workspace_session(workspace_id) as session:
        agents = session.query(Agent).order_by(Agent.created_at).all()
    for agent in agents:
        typer.echo(f"[{agent.role}] {agent.name}")
        typer.echo(f"  性格: {agent.personality}")
        typer.echo(f"  立场: {agent.stance}")


@talk_app.command("send")
def talk_send(
    workspace_id: str = typer.Argument(..., help="Workspace id"),
    message: str = typer.Argument(..., help="Message to the band"),
) -> None:
    """Send one message to the band; the addressed partner replies."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    workspace = get_workspace_or_raise(db, workspace_id)

    target_role = resolve_target_role(message)
    agent = get_agent(db, workspace_id, target_role)
    history = list_messages(db, workspace_id)
    client = build_client(settings)
    prompt = build_agent_prompt(workspace, agent, history, latest_message=message)
    reply = client.complete([LLMMessage(role="user", content=prompt)]).content
    record_message(db, workspace_id, role="author", actor=AUTHOR_ACTOR, content=message)
    record_message(db, workspace_id, role="agent", actor=agent.name, content=reply)

    typer.echo(f"{AUTHOR_ACTOR}: {message}")
    typer.echo(f"{agent.name}: {reply}")

    if not has_proactive_message(db, workspace_id):
        editor = get_agent(db, workspace_id, AgentRole.EDITOR)
        record_message(
            db,
            workspace_id,
            role="agent",
            actor=editor.name,
            content=PROACTIVE_QUESTION,
            payload=PROACTIVE_PAYLOAD,
        )
        typer.echo(f"{editor.name}: {PROACTIVE_QUESTION}")


@talk_app.command("list")
def talk_list(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """List the conversation history for a workspace."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    get_workspace_or_raise(db, workspace_id)
    for message in list_messages(db, workspace_id):
        typer.echo(f"[{message.role}] {message.actor}: {message.content}")
