"""Typer CLI: the primary contract for the M1 milestone."""

from __future__ import annotations

import sys

import typer
from typer.core import TyperGroup

from novel_editorial import __version__
from novel_editorial.core.chat import (
    AUTHOR_ACTOR,
    PROACTIVE_PAYLOAD,
    PROACTIVE_QUESTION,
    build_agent_prompt,
    get_agent,
    get_workspace_or_raise,
    has_proactive_message,
    list_messages,
    record_message,
    resolve_target_role,
)
from novel_editorial.core.config import load_settings
from novel_editorial.core.decision import decide
from novel_editorial.core.draft import (
    build_memory_pack,
    diff_versions,
    find_draft_anywhere,
    generate_draft,
    get_draft_version,
    list_drafts,
    revise_draft,
)
from novel_editorial.core.errors import ErrorCode, NovelError
from novel_editorial.core.logging_setup import configure_logging
from novel_editorial.core.review import add_review, list_reviews, resolve_reviewer
from novel_editorial.core.style import get_style_anchor, set_style_anchor
from novel_editorial.llm.client import LLMMessage, build_client
from novel_editorial.store.db import DB, seed_default_band
from novel_editorial.store.models import Agent, AgentRole, Decision, Workspace

reconfigure = getattr(sys.stdout, "reconfigure", None)
if callable(reconfigure):
    reconfigure(encoding="utf-8", errors="replace")


class NovelGroup(TyperGroup):
    """Translate NovelError to exit code 1 and unexpected errors to exit code 3."""

    def invoke(self, ctx) -> None:
        try:
            super().invoke(ctx)
        except (typer.Exit, typer.Abort):
            raise
        except NovelError as exc:
            typer.echo(f"Error: {exc.message}", err=True)
            exit_code = 2 if exc.code is ErrorCode.USAGE_ERROR else 1
            raise typer.Exit(exit_code) from exc
        except Exception as exc:
            typer.echo(f"Unexpected error: {exc}", err=True)
            raise typer.Exit(3) from exc


app = typer.Typer(cls=NovelGroup, help="Novel Editorial: a layered AI literary editorial office")
works_app = typer.Typer(help="Manage workspaces")
agents_app = typer.Typer(help="Manage editorial partners")
talk_app = typer.Typer(help="Talk with the editorial band")
style_app = typer.Typer(help="Manage style anchors")
memory_app = typer.Typer(help="Inspect writing memory")
draft_app = typer.Typer(help="Manage drafts")
review_app = typer.Typer(help="Review drafts")
decision_app = typer.Typer(help="Author decisions")
app.add_typer(works_app, name="works")
app.add_typer(agents_app, name="agents")
app.add_typer(talk_app, name="talk")
app.add_typer(style_app, name="style")
app.add_typer(memory_app, name="memory")
app.add_typer(draft_app, name="draft")
app.add_typer(review_app, name="review")
app.add_typer(decision_app, name="decision")


@app.callback(invoke_without_command=True)
def main(
    verbose: bool = typer.Option(False, "--verbose", help="Enable debug logging"),
    show_version: bool = typer.Option(False, "--version", help="Show version and exit"),
) -> None:
    if show_version:
        typer.echo(__version__)
        raise typer.Exit()
    settings = load_settings()
    configure_logging("DEBUG" if verbose else settings.log_level)


@app.command("init")
def init() -> None:
    """Initialize data directory and configuration."""
    settings = load_settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    DB(settings).init_schema()
    if settings.config_path.exists():
        typer.echo(f"config exists: {settings.config_path} (kept)")
    else:
        settings.config_path.write_text(
            "# Generated by `novel-editorial init`. Copy config.example.toml for defaults.\n"
            "[defaults]\n",
            encoding="utf-8",
        )
    typer.echo(f"initialized: {settings.data_dir}")


@app.command()
def health() -> None:
    """Check configuration and database connectivity."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    db.ping()
    typer.echo("ok")


@app.command("version")
def version() -> None:
    """Print the current version."""
    typer.echo(__version__)


@works_app.command("create")
def works_create(
    title: str = typer.Argument(..., help="Work title"),
    genre: str = typer.Option("", "--genre", help="Genre"),
    description: str = typer.Option("", "--description", help="Short description"),
) -> None:
    """Create a workspace with a default editorial band."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspace = Workspace(title=title, genre=genre, description=description)
        session.add(workspace)
        session.commit()
        workspace_id = workspace.id
    db.create_workspace_db(workspace_id)
    seed_default_band(db, workspace_id)
    typer.echo(f"created workspace {workspace_id}: {title}")


@works_app.command("list")
def works_list() -> None:
    """List all workspaces."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspaces = session.query(Workspace).order_by(Workspace.created_at).all()
    for workspace in workspaces:
        typer.echo(f"{workspace.id}  {workspace.title}  {workspace.genre}")
    if not workspaces:
        typer.echo("no workspaces yet")


@works_app.command("show")
def works_show(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show a workspace and its editorial band."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        workspace = session.get(Workspace, workspace_id)
        if workspace is None:
            raise NovelError(ErrorCode.NOT_FOUND, f"workspace not found: {workspace_id}")
        title = workspace.title
        genre = workspace.genre
        description = workspace.description
    typer.echo(f"id: {workspace_id}")
    typer.echo(f"title: {title}")
    typer.echo(f"genre: {genre}")
    if description:
        typer.echo(f"description: {description}")
    with db.workspace_session(workspace_id) as session:
        agents = session.query(Agent).order_by(Agent.created_at).all()
    typer.echo("band:")
    for agent in agents:
        typer.echo(f"  {agent.role}: {agent.name}")


@agents_app.command("show")
def agents_show(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show the workspace's editorial band with full profiles."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    with db.global_session() as session:
        if session.get(Workspace, workspace_id) is None:
            raise NovelError(ErrorCode.NOT_FOUND, f"workspace not found: {workspace_id}")
    with db.workspace_session(workspace_id) as session:
        agents = session.query(Agent).order_by(Agent.created_at).all()
    for agent in agents:
        typer.echo(f"[{agent.role}] {agent.name}")
        typer.echo(f"  性格: {agent.personality}")
        typer.echo(f"  立场: {agent.stance}")


@talk_app.command("send")
def talk_send(
    workspace_id: str = typer.Argument(..., help="Workspace id"),
    message: str = typer.Argument(..., help="Message to the band"),
) -> None:
    """Send one message to the band; the addressed partner replies."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    workspace = get_workspace_or_raise(db, workspace_id)

    target_role = resolve_target_role(message)
    agent = get_agent(db, workspace_id, target_role)
    history = list_messages(db, workspace_id)
    client = build_client(settings)
    prompt = build_agent_prompt(workspace, agent, history, latest_message=message)
    reply = client.complete([LLMMessage(role="user", content=prompt)]).content
    record_message(db, workspace_id, role="author", actor=AUTHOR_ACTOR, content=message)
    record_message(db, workspace_id, role="agent", actor=agent.name, content=reply)

    typer.echo(f"{AUTHOR_ACTOR}: {message}")
    typer.echo(f"{agent.name}: {reply}")

    if not has_proactive_message(db, workspace_id):
        editor = get_agent(db, workspace_id, AgentRole.EDITOR)
        record_message(
            db,
            workspace_id,
            role="agent",
            actor=editor.name,
            content=PROACTIVE_QUESTION,
            payload=PROACTIVE_PAYLOAD,
        )
        typer.echo(f"{editor.name}: {PROACTIVE_QUESTION}")


@talk_app.command("list")
def talk_list(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """List the conversation history for a workspace."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    get_workspace_or_raise(db, workspace_id)
    for message in list_messages(db, workspace_id):
        typer.echo(f"[{message.role}] {message.actor}: {message.content}")


@style_app.command("set")
def style_set(
    workspace_id: str = typer.Argument(..., help="Workspace id"),
    description: str = typer.Option("", "--description", help="Style description"),
    forbidden: str = typer.Option("", "--forbidden", help="Forbidden words, comma separated"),
) -> None:
    """Set the workspace style anchor."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    get_workspace_or_raise(db, workspace_id)
    set_style_anchor(db, workspace_id, description=description, forbidden_words=forbidden)
    typer.echo(f"style anchor updated: {workspace_id}")


@style_app.command("show")
def style_show(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show the workspace style anchor."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    get_workspace_or_raise(db, workspace_id)
    anchor = get_style_anchor(db, workspace_id)
    typer.echo(f"description: {anchor.description or '(empty)'}")
    typer.echo(f"forbidden: {anchor.forbidden_words or '(empty)'}")


@memory_app.command("pack")
def memory_pack(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show the writing memory pack for a workspace."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    typer.echo(build_memory_pack(db, workspace_id))


@draft_app.command("generate")
def draft_generate(
    workspace_id: str = typer.Argument(..., help="Workspace id"),
    title: str = typer.Option("未命名章节", "--title", help="Chapter title"),
) -> None:
    """Generate a draft version (writer + memory pack + LLM)."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    client = build_client(settings)
    draft = generate_draft(db, workspace_id, title=title, client=client)
    typer.echo(f"draft {draft.id} {draft.title} now at v{draft.current_version}")


@draft_app.command("revise")
def draft_revise(
    draft_id: str = typer.Argument(..., help="Draft id"),
    reason: str = typer.Option("revision", "--reason", help="Reason for the revision"),
) -> None:
    """Re-generate a draft as a new version (writer + LLM)."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    client = build_client(settings)
    revised = revise_draft(db, draft.workspace_id, draft_id, reason=reason, client=client)
    typer.echo(f"draft {revised.id} {revised.title} now at v{revised.current_version}")


@draft_app.command("list")
def draft_list(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """List drafts in a workspace."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    get_workspace_or_raise(db, workspace_id)
    for draft in list_drafts(db, workspace_id):
        typer.echo(f"{draft.id}  {draft.title}  v{draft.current_version}  {draft.status}")


@draft_app.command("show")
def draft_show(draft_id: str = typer.Argument(..., help="Draft id")) -> None:
    """Show a draft with its latest version content."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    version = get_draft_version(db, draft.workspace_id, draft_id, draft.current_version)
    typer.echo(f"{draft.title} (v{draft.current_version}, {draft.status})")
    typer.echo(f"reason: {version.reason}")
    typer.echo("---")
    typer.echo(version.content)


@draft_app.command("diff")
def draft_diff(
    draft_id: str = typer.Argument(..., help="Draft id"),
    version_a: int = typer.Argument(..., help="Version A"),
    version_b: int = typer.Argument(..., help="Version B"),
) -> None:
    """Show the diff between two versions of a draft."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    first = get_draft_version(db, draft.workspace_id, draft_id, version_a)
    second = get_draft_version(db, draft.workspace_id, draft_id, version_b)
    output = diff_versions(first, second)
    typer.echo(output if output else "no differences")


@review_app.command("add")
def review_add(
    draft_id: str = typer.Argument(..., help="Draft id"),
    source: str = typer.Option("作者", "--from", help="Reviewer: 作者/总编/责编/写手/审稿"),
    content: str = typer.Option(..., "--content", help="Review comment"),
) -> None:
    """Add a review comment to a draft."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    role, actor = resolve_reviewer(db, draft.workspace_id, source)
    add_review(db, draft.workspace_id, draft_id, role=role, actor=actor, content=content)
    typer.echo(f"review added by {actor}: {content}")


@review_app.command("list")
def review_list(draft_id: str = typer.Argument(..., help="Draft id")) -> None:
    """List review comments for a draft."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    reviews = list_reviews(db, draft.workspace_id, draft_id)
    for review in reviews:
        typer.echo(f"[{review.role}] {review.actor}: {review.content}")
    if not reviews:
        typer.echo("no reviews yet")


@decision_app.command("list")
def decision_list(draft_id: str = typer.Argument(..., help="Draft id")) -> None:
    """List decision records for a draft."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    with db.workspace_session(draft.workspace_id) as session:
        decisions = (
            session.query(Decision)
            .filter_by(draft_id=draft_id)
            .order_by(Decision.created_at)
            .all()
        )
    for decision in decisions:
        suffix = f": {decision.content}" if decision.content else ""
        typer.echo(f"[{decision.action}] {decision.actor}{suffix}")
    if not decisions:
        typer.echo("no decisions yet")


@decision_app.command("accept")
def decision_accept(draft_id: str = typer.Argument(..., help="Draft id")) -> None:
    """Accept a draft as the author."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    decide(db, draft.workspace_id, draft_id, action="accept")
    typer.echo(f"draft {draft_id} accepted")


@decision_app.command("reject")
def decision_reject(draft_id: str = typer.Argument(..., help="Draft id")) -> None:
    """Reject a draft as the author."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    decide(db, draft.workspace_id, draft_id, action="reject")
    typer.echo(f"draft {draft_id} rejected")


@decision_app.command("note")
def decision_note(
    draft_id: str = typer.Argument(..., help="Draft id"),
    content: str = typer.Option(..., "--content", help="Note text"),
) -> None:
    """Leave a note on a draft without changing its status."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    draft = find_draft_anywhere(db, draft_id)
    decide(db, draft.workspace_id, draft_id, action="note", content=content)
    typer.echo(f"note added to draft {draft_id}")
