"""Typer CLI: the primary contract for the M1 milestone."""

from __future__ import annotations

import sys

import typer
from typer.core import TyperGroup

from novel_editorial import __version__
from novel_editorial.cli.agents import agents_app
from novel_editorial.cli.decision import decision_app
from novel_editorial.cli.draft import draft_app
from novel_editorial.cli.events import events_app
from novel_editorial.cli.memory import memory_app
from novel_editorial.cli.plot import plot_app
from novel_editorial.cli.quality import quality_app
from novel_editorial.cli.review import review_app
from novel_editorial.cli.style import style_app
from novel_editorial.cli.talk import talk_app
from novel_editorial.cli.works import works_app
from novel_editorial.core.config import load_settings
from novel_editorial.core.demo import run_demo
from novel_editorial.core.errors import ErrorCode, NovelError
from novel_editorial.core.log import build_workspace_log
from novel_editorial.core.logging_setup import configure_logging
from novel_editorial.core.views import search_all_layers
from novel_editorial.store.db import DB

reconfigure = getattr(sys.stdout, "reconfigure", None)
if callable(reconfigure):
    reconfigure(encoding="utf-8", errors="replace")
stderr_reconfigure = getattr(sys.stderr, "reconfigure", None)
if callable(stderr_reconfigure):
    stderr_reconfigure(encoding="utf-8", errors="replace")


class NovelGroup(TyperGroup):
    """Translate NovelError to exit code 1 and unexpected errors to exit code 3."""

    def invoke(self, ctx) -> None:
        try:
            super().invoke(ctx)
        except (typer.Exit, typer.Abort):
            raise
        except NovelError as exc:
            typer.echo(f"Error: {exc.message}", err=True)
            exit_code = 2 if exc.code is ErrorCode.USAGE_ERROR else 1
            raise typer.Exit(exit_code) from exc
        except Exception as exc:
            typer.echo(f"Unexpected error: {exc}", err=True)
            raise typer.Exit(3) from exc


app = typer.Typer(cls=NovelGroup, help="Novel Editorial: a layered AI literary editorial office")
app.add_typer(works_app, name="works")
app.add_typer(agents_app, name="agents")
app.add_typer(talk_app, name="talk")
app.add_typer(style_app, name="style")
app.add_typer(memory_app, name="memory")
app.add_typer(draft_app, name="draft")
app.add_typer(review_app, name="review")
app.add_typer(decision_app, name="decision")
app.add_typer(quality_app, name="quality")
app.add_typer(plot_app, name="plot")
app.add_typer(events_app, name="events")


@app.callback(invoke_without_command=True)
def main(
    verbose: bool = typer.Option(False, "--verbose", help="Enable debug logging"),
    show_version: bool = typer.Option(False, "--version", help="Show version and exit"),
) -> None:
    if show_version:
        typer.echo(__version__)
        raise typer.Exit()
    settings = load_settings()
    configure_logging("DEBUG" if verbose else settings.log_level)


@app.command("init")
def init() -> None:
    """Initialize data directory and configuration."""
    settings = load_settings()
    settings.data_dir.mkdir(parents=True, exist_ok=True)
    DB(settings).init_schema()
    if settings.config_path.exists():
        typer.echo(f"config exists: {settings.config_path} (kept)")
    else:
        settings.config_path.write_text(
            "# Generated by `novel-editorial init`. Copy config.example.toml for defaults.\n"
            "[defaults]\n",
            encoding="utf-8",
        )
    typer.echo(f"initialized: {settings.data_dir}")


@app.command()
def health() -> None:
    """Check configuration and database connectivity."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    db.ping()
    typer.echo("ok")


@app.command("version")
def version() -> None:
    """Print the current version."""
    typer.echo(__version__)


@app.command("demo")
def demo() -> None:
    """Run the M1 end-to-end demo (uses mock LLM unless a key is configured)."""
    settings = load_settings()
    result = run_demo(settings)
    typer.echo(f"workspace: {result['workspace_id']}")
    typer.echo(f"draft: {result['draft_id']}")
    typer.echo(f"quality passed: {result['quality'].passed} (score {result['quality'].score})")
    if result["accepted"]:
        typer.echo("draft accepted. Run `novel-editorial log <workspace_id>` to review the flow.")
    else:
        typer.echo(
            "draft rejected by the quality gate (demo stops at the gate). "
            "Run `novel-editorial log <workspace_id>` to review the flow."
        )


@app.command("log")
def log_workspace(workspace_id: str = typer.Argument(..., help="Workspace id")) -> None:
    """Show the full workflow log for a workspace."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    typer.echo(build_workspace_log(db, workspace_id))


@app.command("inspect")
def inspect_workspace(
    workspace_id: str = typer.Argument(..., help="Workspace id"),
    keyword: str = typer.Argument(..., help="Search keyword"),
) -> None:
    """Search every workspace layer with source citations."""
    settings = load_settings()
    db = DB(settings)
    db.init_schema()
    typer.echo(search_all_layers(db, workspace_id, keyword))
