"""add agent mood

Revision ID: 2c8ab7642c70
Revises: ede724222072
Create Date: 2026-08-13 21:47:10.144025

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c8ab7642c70"
down_revision: str | Sequence[str] | None = "ede724222072"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents", sa.Column("mood", sa.Text(), nullable=False, server_default="平静")
    )
    op.execute("UPDATE agents SET mood='沉稳' WHERE role='editor_in_chief'")
    op.execute("UPDATE agents SET mood='精力充沛' WHERE role='editor'")
    op.execute("UPDATE agents SET mood='平静' WHERE role='writer'")
    op.execute("UPDATE agents SET mood='冷静' WHERE role='reviewer'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "mood")
    # ### end Alembic commands ###
