"""add style anchors and drafts

Revision ID: 53d93a53fe74
Revises: 29bc454a0e29
Create Date: 2026-08-13 11:02:34.708559

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53d93a53fe74'
down_revision: str | Sequence[str] | None = '29bc454a0e29'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_draft_versions_draft_id'), 'draft_versions', ['draft_id'], unique=False
    )
    op.create_table('drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_workspace_id'), 'drafts', ['workspace_id'], unique=False)
    op.create_table('style_anchors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('forbidden_words', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_style_anchors_workspace_id'),
        'style_anchors',
        ['workspace_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_style_anchors_workspace_id'), table_name='style_anchors')
    op.drop_table('style_anchors')
    op.drop_index(op.f('ix_drafts_workspace_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_draft_versions_draft_id'), table_name='draft_versions')
    op.drop_table('draft_versions')
    # ### end Alembic commands ###
