"""add unique constraint on draft versions

Revision ID: 6a137bafe746
Revises: 53d93a53fe74
Create Date: 2026-08-13 11:19:02.547523

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a137bafe746'
down_revision: str | Sequence[str] | None = '53d93a53fe74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions') as batch_op:
        batch_op.create_unique_constraint(
            'uq_draft_versions_draft_version', ['draft_id', 'version']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions') as batch_op:
        batch_op.drop_constraint('uq_draft_versions_draft_version', type_='unique')
    # ### end Alembic commands ###
