"""add agent memories table

Revision ID: ede724222072
Revises: f1f5f128b371
Create Date: 2026-08-13 19:31:42.395806

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ede724222072'
down_revision: str | Sequence[str] | None = 'f1f5f128b371'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_memories',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('workspace_id', sa.String(length=32), nullable=False),
        sa.Column('agent_id', sa.String(length=32), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_agent_memories_agent_id'), 'agent_memories', ['agent_id'], unique=False
    )
    op.create_index(
        op.f('ix_agent_memories_workspace_id'),
        'agent_memories',
        ['workspace_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_memories_workspace_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_agent_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
