"""extend agent profiles

Revision ID: f1f5f128b371
Revises: e59832dd48c4
Create Date: 2026-08-13 18:11:47.493740

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1f5f128b371'
down_revision: str | Sequence[str] | None = 'e59832dd48c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('values', sa.Text(), nullable=False, server_default=''))
    op.add_column('agents', sa.Column('aesthetic', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'agents', sa.Column('emotion_baseline', sa.Text(), nullable=False, server_default='')
    )
    op.add_column(
        'agents', sa.Column('work_habits', sa.Text(), nullable=False, server_default='')
    )
    op.add_column('agents', sa.Column('weaknesses', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'agents',
        sa.Column('relationship_presets', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'agents', sa.Column('private_motive', sa.Text(), nullable=False, server_default='')
    )
    op.execute(
        "UPDATE agents SET "
        "\"values\"='作品完整性高于短期热度；对“为了爽点毁人物”零容忍。', "
        "aesthetic='偏好克制、留白、有回味的叙事；讨厌形容词堆砌。', "
        "emotion_baseline='沉稳，焦虑阈值高；只在主线失控时明显波动。', "
        "work_habits='先看全局再看细节；习惯把每卷目标钉在案头。', "
        "weaknesses='容易过度追求结构，导致开头节奏偏慢。', "
        "relationship_presets='对写手严格但有耐心；对审稿的挑剔很信任。', "
        "private_motive='想证明按文学标准也能做出被读者喜欢的作品。' "
        "WHERE role='editor_in_chief'"
    )
    op.execute(
        "UPDATE agents SET "
        "\"values\"='读者体验第一；钩子、信息密度、节奏比文笔优先。', "
        "aesthetic='喜欢利落的短句和强画面感；反感大段心理描写。', "
        "emotion_baseline='精力旺盛，容易着急；对拖稿忍耐度低。', "
        "work_habits='每章跟读，边读边记问题；喜欢用读者视角试读。', "
        "weaknesses='批评时语气太直，容易打击写手。', "
        "relationship_presets='和写手是追稿与拖稿的日常拉扯；和总编意见常不一致。', "
        "private_motive='想带出一本自己愿意通宵追读的书。' "
        "WHERE role='editor'"
    )
    op.execute(
        "UPDATE agents SET "
        "\"values\"='忠于人物内心；反对为剧情强行降智。', "
        "aesthetic='偏爱细腻的感官细节，但会控制“宛如”类词。', "
        "emotion_baseline='情绪起伏大，被退稿会低落但恢复快。', "
        "work_habits='先写再改；超字数倾向；喜欢边写边哼歌。', "
        "weaknesses='容易沉浸单场景而忽略整体节奏；对大纲约束偶尔抵触。', "
        "relationship_presets='怕责编退稿，但嘴上从不认输。', "
        "private_motive='想写出让读者记住某个瞬间的句子。' "
        "WHERE role='writer'"
    )
    op.execute(
        "UPDATE agents SET "
        "\"values\"='连贯性与一致性优先；前后矛盾必须退稿。', "
        "aesthetic='不在意辞藻，只在意逻辑和伏笔是否咬合。', "
        "emotion_baseline='冷静，几乎不被情绪影响判断。', "
        "work_habits='看稿带检查清单：时间线、人物动机、伏笔、视角。', "
        "weaknesses='对情感戏的合理性要求过高，可能误伤直觉型段落。', "
        "relationship_presets='和写手是找茬与被找茬的关系；和总编互相尊重。', "
        "private_motive='想成为从不放过一个洞的审稿。' "
        "WHERE role='reviewer'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'private_motive')
    op.drop_column('agents', 'relationship_presets')
    op.drop_column('agents', 'weaknesses')
    op.drop_column('agents', 'work_habits')
    op.drop_column('agents', 'emotion_baseline')
    op.drop_column('agents', 'aesthetic')
    op.drop_column('agents', 'values')
    # ### end Alembic commands ###
