"""extend agent profiles

Revision ID: f1f5f128b371
Revises: e59832dd48c4
Create Date: 2026-08-13 18:11:47.493740

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1f5f128b371'
down_revision: str | Sequence[str] | None = 'e59832dd48c4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('values', sa.Text(), nullable=False, server_default=''))
    op.add_column('agents', sa.Column('aesthetic', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'agents', sa.Column('emotion_baseline', sa.Text(), nullable=False, server_default='')
    )
    op.add_column(
        'agents', sa.Column('work_habits', sa.Text(), nullable=False, server_default='')
    )
    op.add_column('agents', sa.Column('weaknesses', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'agents',
        sa.Column('relationship_presets', sa.Text(), nullable=False, server_default=''),
    )
    op.add_column(
        'agents', sa.Column('private_motive', sa.Text(), nullable=False, server_default='')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'private_motive')
    op.drop_column('agents', 'relationship_presets')
    op.drop_column('agents', 'weaknesses')
    op.drop_column('agents', 'work_habits')
    op.drop_column('agents', 'emotion_baseline')
    op.drop_column('agents', 'aesthetic')
    op.drop_column('agents', 'values')
    # ### end Alembic commands ###
